### ISSUE TITLE
lobe-chat调用o1-preview时出现错误

### ISSUE THREAD

**Issue by SHLE1** [VoAPI/VoAPI#4]
lobe-chat调用o1-preview时出现错误，报错如下：
```
{
  "error": {
    "name": "TypeError",
    "stack": "TypeError: Cannot read properties of undefined (reading 'map')\n    at Object.start (https://lobe.**.**/_next/static/chunks/22439-82bd331bbdac8b78.js:1:14031)\n    at D (https://lobe.**.**/_next/static/chunks/22439-82bd331bbdac8b78.js:1:13977)\n    at Object.chat (https://lobe.**.**/_next/static/chunks/22439-82bd331bbdac8b78.js:1:15633)\n    at async n (https://lobe.**.**/_next/static/chunks/22439-82bd331bbdac8b78.js:1:56271)\n    at async https://lobe.**.**/_next/static/chunks/22439-82bd331bbdac8b78.js:1:51007",
    "message": "Cannot read properties of undefined (reading 'map')"
  },
  "endpoint": "https://demo.vo****pi.top/",
  "provider": "openai"
}
```
在lobe-chat官方查找issue后发现有[类似情况](https://github.com/lobehub/lobe-chat/issues/4069)，此情况在直接在lobe-chat填入api-url和key时会出现。同时，套一层new-api中转会出现超时错误，而new-api后台不会出现该次请求，voapi后台则出现该次请求。

**Comment by Licoy** [comment]
看看请求响应，这个错误是lobe的前端报错了导致的，应该是响应字段或者网络请求失败造成的。
